#
#   __         _____                     _            _____  _                       _
#   \ \      / ____|                    | |          |  __ \(_)                     | |
#    \ \    | |     ___  _ __  ___  ___ | | ___      | |  | |_ ___  ___ ___  _ __ __| |
#     > >   | |    / _ \| '_ \/ __|/ _ \| |/ _ \     | |  | | / __|/ __/ _ \| '__/ _` |
#    / /    | |___| (_) | | | \__ \ (_) | |  __/     | |__| | \__ \ (_| (_) | | | (_| |
#   /_/      \_____\___/|_| |_|___/\___/|_|\___|     |_____/|_|___/\___\___/|_|  \__,_|
#
#     By: Niix-dan
#     Source: https://github.com/Niix-Dan/ConsoleDiscord
#

# Discord Bot Infos
Discord-Bot:
  # Discord Applications - https://discord.com/developers/applications
  Token: ""
  Channel: ""

  # BlockedCmds: ["op", "stop"] - Commands that you don't want anyone to use in the console
  BlockedCmds: []

  # Whitelist of admins that can use the console in discord
  Whitelist:
    Enabled: false
    List: [ "YOUR-DISCORD-ID" ]
    Message: "Womp womp, no commands for you"

Messages:
  Discord:
    MessageLimit: "\n\nThis message exceeded discord's 2,000 character limit. To see the complete log look in the console!"

  InGame:
    NoPerm: "&d[ConsoleDiscord] &cNope."

Config:
  IgnoreWords: [] # if the log message contains one of these words, it will be ignored and not sent to the discord.

  LogDelay: 20 # Delay between console logs checks, to send to the discord (in ticks)
  LibsUpdater: true # Automatically update libraries on plugin startup
  LogLevel: "INFO" # Log level for plugin (INFO, WARNING, DEBUG)

  Filter: # Filter commands from discord (Advanced users only)
    Enabled: false
    RegEx: ""
    Replace: ""

  # Please don't touch unless you know what you're doing
  Config_version: 1.0
  Libs_version: 1.0