name: ConsoleDiscord
version: '1.1.2'
main: niix.dan.consolediscord.ConsoleDiscord
load: STARTUP
authors: [Niix-Dan]
description: A plugin that links your console to a discord channel
website: https://github.com/Niix-Dan/ConsoleDiscord

